/* =====================================================================
 * Authentication.
 *
 * Why not Google sign-in? The guest QR page must open for anyone with no
 * account, so the web app is deployed as "anyone". Staff therefore sign in
 * with a username and password kept in the Users tab.
 *
 *  - Passwords are salted and hashed (iterated HMAC-SHA256); never stored.
 *  - Passwords are generated by an admin (random, shown once); staff can
 *    change their own.
 *  - Session tokens are 244 random bits; only their hash is stored.
 *  - Failed logins are throttled per username.
 * ===================================================================== */

const Auth = (function () {
  function hashPassword(password, salt) {
    const rounds = Math.max(1, Config.num('auth_rounds'));
    let h = String(salt);
    for (let i = 0; i < rounds; i++) {
      h = bytesToHex_(Utilities.computeHmacSha256Signature(h, String(password) + ':' + salt));
    }
    return h;
  }

  function constantTimeEquals(a, b) {
    if (a.length !== b.length) return false;
    let d = 0;
    for (let i = 0; i < a.length; i++) d |= a.charCodeAt(i) ^ b.charCodeAt(i);
    return d === 0;
  }

  function publicUser(u) { return { id: u.id, username: u.username, name: u.display_name, role: u.role }; }

  function validPassword(pw) {
    if (typeof pw !== 'string' || pw.length < 8) throw HttpError_(400, 'Password must be at least 8 characters');
    if (pw.length > 100) throw HttpError_(400, 'Password is too long');
  }

  function validUsername(u) {
    if (!/^[A-Za-z0-9._-]{3,32}$/.test(u)) throw HttpError_(400, 'Username must be 3-32 letters, numbers, dot, dash or underscore');
  }

  function findUserByName(username) {
    const n = String(username || '').trim().toLowerCase();
    const rows = Store.all('Users');
    for (let i = 0; i < rows.length; i++) if (rows[i].username.toLowerCase() === n) return rows[i];
    return null;
  }

  function throttleKey(username) { return 'wg:fail:' + sha256Hex_(String(username || '').toLowerCase()); }

  function login(username, password) {
    const cache = CacheService.getScriptCache();
    const key = throttleKey(username);
    const fails = parseInt(cache.get(key) || '0', 10);
    if (fails >= 5) throw HttpError_(429, 'Too many failed attempts. Try again in 10 minutes.');
    const u = findUserByName(username);
    // Always hash, so unknown users cost the same as wrong passwords.
    const computed = hashPassword(String(password || ''), u ? u.salt : 'no-such-user');
    const ok = u && u.active && constantTimeEquals(computed, u.hash);
    if (!ok) {
      cache.put(key, String(fails + 1), 600);
      throw HttpError_(401, 'Incorrect username or password');
    }
    cache.remove(key);
    return Locks.run(function () {
      const token = randomToken_();
      const hours = Config.num('session_hours') || 12;
      const now = nowIso_();
      // opportunistic cleanup of expired sessions
      Store.all('Sessions').filter(function (s) { return s.expires_at < now; }).reverse().forEach(function (s) { Store.remove('Sessions', s._row); });
      Store.insert('Sessions', { token_hash: sha256Hex_(token), user_id: u.id, expires_at: new Date(Date.now() + hours * 3600e3).toISOString() });
      audit_(u, 'login', '');
      return { token: token, user: publicUser(u) };
    });
  }

  /** Resolve a session token to a user, or null. Result cached for 60 s. */
  function userFromToken(token) {
    if (!token || typeof token !== 'string' || token.length !== 64) return null;
    const hash = sha256Hex_(token);
    const cache = CacheService.getScriptCache();
    const hit = cache.get('wg:s:' + hash);
    if (hit) {
      const c = JSON.parse(hit);
      if (c.exp > Date.now()) return c.user;
    }
    const s = Store.find('Sessions', 'token_hash', hash);
    if (!s || s.expires_at < nowIso_()) return null;
    const u = Store.find('Users', 'id', s.user_id);
    if (!u || !u.active) return null;
    const user = publicUser(u);
    cache.put('wg:s:' + hash, JSON.stringify({ user: user, exp: Date.now() + 60000 }), 60);
    return user;
  }

  function logout(token) {
    if (!token || typeof token !== 'string') return;
    const hash = sha256Hex_(token);
    CacheService.getScriptCache().remove('wg:s:' + hash);
    Locks.run(function () {
      const s = Store.find('Sessions', 'token_hash', hash);
      if (s) Store.remove('Sessions', s._row);
    });
  }

  function killSessions(userId) {
    Store.all('Sessions').filter(function (s) { return s.user_id === userId; }).reverse().forEach(function (s) { Store.remove('Sessions', s._row); });
  }

  // ---- user administration (admin only, enforced in the router) ---------
  function listUsers() {
    return Store.all('Users').map(function (u) { return { id: u.id, username: u.username, name: u.display_name, role: u.role, active: u.active, createdAt: u.created_at }; });
  }

  function nextUserId() {
    return Store.all('Users').reduce(function (m, u) { return Math.max(m, u.id); }, 0) + 1;
  }

  function createUser(actor, input) {
    const username = clean_(input.username, 32);
    const name = clean_(input.name, 80);
    validUsername(username);
    if (!name) throw HttpError_(400, 'Name is required');
    if (!ROLES[input.role]) throw HttpError_(400, 'Choose a valid role');
    return Locks.run(function () {
      if (findUserByName(username)) throw HttpError_(409, 'That username already exists');
      const password = input.password ? String(input.password) : randomPassword_(14);
      validPassword(password);
      const salt = randomToken_().slice(0, 32);
      const u = Store.insert('Users', { id: nextUserId(), username: username, display_name: name, role: input.role, salt: salt, hash: hashPassword(password, salt), active: true, created_at: nowIso_() });
      audit_(actor, 'user.create', username + ' (' + input.role + ')');
      Store.bump();
      return { user: { id: u.id, username: u.username, name: u.display_name, role: u.role, active: true }, password: password };
    });
  }

  function activeAdmins() { return Store.all('Users').filter(function (u) { return u.role === 'admin' && u.active; }); }

  function setActive(actor, id, active) {
    return Locks.run(function () {
      const u = Store.find('Users', 'id', id);
      if (!u) throw HttpError_(404, 'User not found');
      if (!active && u.role === 'admin' && activeAdmins().length <= 1 && u.active) throw HttpError_(409, 'You cannot deactivate the last active admin');
      if (!active && actor && actor.id === id) throw HttpError_(409, 'You cannot deactivate your own account');
      Store.update('Users', u._row, { active: !!active });
      if (!active) killSessions(id);
      audit_(actor, active ? 'user.activate' : 'user.deactivate', u.username);
      Store.bump();
      return { ok: true };
    });
  }

  /** Admin: change a user's name or role. */
  function updateUser(actor, id, input) {
    input = input || {};
    return Locks.run(function () {
      const u = Store.find('Users', 'id', id);
      if (!u) throw HttpError_(404, 'User not found');
      const patch = {};
      if (input.name !== undefined) { patch.display_name = clean_(input.name, 80); if (!patch.display_name) throw HttpError_(400, 'Name is required'); }
      if (input.role !== undefined) {
        if (!ROLES[input.role]) throw HttpError_(400, 'Choose a valid role');
        if (u.role === 'admin' && input.role !== 'admin' && u.active && activeAdmins().length <= 1) throw HttpError_(409, 'You cannot remove the last active admin');
        if (actor && actor.id === id && input.role !== 'admin') throw HttpError_(409, 'You cannot remove your own admin role');
        patch.role = input.role;
      }
      const oldRole = u.role; // read before update: Store.update refreshes the row object in place
      Store.update('Users', u._row, patch);
      if (patch.role && patch.role !== oldRole) killSessions(id); // new role applies at next sign-in
      audit_(actor, 'user.update', u.username + (patch.role && patch.role !== oldRole ? ' role ' + oldRole + ' -> ' + patch.role : ''));
      Store.bump();
      return { ok: true };
    });
  }

  /** Admin: delete a user. Their past actions stay in the history (shown without a name). */
  function deleteUser(actor, id) {
    return Locks.run(function () {
      const u = Store.find('Users', 'id', id);
      if (!u) throw HttpError_(404, 'User not found');
      if (actor && actor.id === id) throw HttpError_(409, 'You cannot delete your own account');
      if (u.role === 'admin' && u.active && activeAdmins().length <= 1) throw HttpError_(409, 'You cannot delete the last active admin');
      killSessions(id);
      Store.remove('Users', Store.find('Users', 'id', id)._row);
      audit_(actor, 'user.delete', u.username);
      Store.bump();
      return { ok: true };
    });
  }

  function resetPassword(actor, id) {
    return Locks.run(function () {
      const u = Store.find('Users', 'id', id);
      if (!u) throw HttpError_(404, 'User not found');
      const password = randomPassword_(14);
      const salt = randomToken_().slice(0, 32);
      Store.update('Users', u._row, { salt: salt, hash: hashPassword(password, salt) });
      killSessions(id);
      audit_(actor, 'user.reset_password', u.username);
      return { password: password };
    });
  }

  function changeOwnPassword(user, current, next) {
    validPassword(next);
    return Locks.run(function () {
      const u = Store.find('Users', 'id', user.id);
      if (!u || !constantTimeEquals(hashPassword(String(current || ''), u.salt), u.hash)) throw HttpError_(403, 'Current password is incorrect');
      const salt = randomToken_().slice(0, 32);
      Store.update('Users', u._row, { salt: salt, hash: hashPassword(next, salt) });
      audit_(user, 'user.change_password', u.username);
      return { ok: true };
    });
  }

  return { updateUser: updateUser, deleteUser: deleteUser, login: login, logout: logout, userFromToken: userFromToken, listUsers: listUsers, createUser: createUser,
    setActive: setActive, resetPassword: resetPassword, changeOwnPassword: changeOwnPassword, hashPassword: hashPassword, validPassword: validPassword };
})();
