'use strict';
/**
 * Builds the three files that go into Google Apps Script:
 *   dist/apps-script/Code.gs         all server code (one file, easy to paste)
 *   dist/apps-script/Index.html      the whole browser app (HTML + CSS + JS inline)
 *   dist/apps-script/appsscript.json manifest (timezone, web app access)
 * Run: npm run build
 */
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');
const read = (...p) => fs.readFileSync(path.join(ROOT, ...p), 'utf8');
const list = (dir, ext) => fs.readdirSync(path.join(ROOT, dir)).filter((f) => f.endsWith(ext)).sort();

function buildCode() {
  const parts = [];
  parts.push('/* Waiting Guest: server code. GENERATED by scripts/build.js. Edit files in src/server, not this file. */\n');
  // Wrapped so the library is not a top-level function: every top-level function in Apps Script
  // can be called by any web-app visitor through google.script.run.
  parts.push('/* ---- vendor: qrcode-generator (MIT, Kazuhiko Arase) ---- */\nconst QRCODE_ = (function () {\n' + read('src/vendor/qrcode-generator.js') + '\nreturn qrcode;\n})();\n');
  for (const f of list('src/server', '.js')) parts.push(`\n/* ---- src/server/${f} ---- */\n` + read('src/server', f));
  return parts.join('\n');
}

function buildIndex() {
  const css = list('src/web/css', '.css').map((f) => read('src/web/css', f)).join('\n');
  const logo = fs.readFileSync(path.join(ROOT, 'src/web/assets/rixos-logo.png')).toString('base64');
  const assets = `const WG_ASSETS = { logo: 'data:image/png;base64,${logo}' };\n`;
  const js = assets + list('src/web/js', '.js').map((f) => `/* ---- ${f} ---- */\n` + read('src/web/js', f)).join('\n');
  if (/<\?/.test(js) || /<\/script/i.test(js)) throw new Error('Client JS must not contain "<?" or "</script"');
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
<title>Waiting Guest</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Source+Serif+4:opsz,wght@8..60,500;8..60,600&family=Plus+Jakarta+Sans:wght@400;500;600;700;800&family=Noto+Sans+Arabic:wght@400;600;700&display=swap">
<style>
${css}
</style>
</head>
<body>
<div id="root"></div>
<script>window.WG_BOOT = <?!= boot ?>;</script>
<script>
${js}
</script>
</body>
</html>
`;
}

const MANIFEST = {
  timeZone: 'Asia/Dubai',
  exceptionLogging: 'STACKDRIVER',
  runtimeVersion: 'V8',
  webapp: { executeAs: 'USER_DEPLOYING', access: 'ANYONE_ANONYMOUS' },
  oauthScopes: [
    // Full spreadsheets scope: a standalone script opens its database sheet by id.
    'https://www.googleapis.com/auth/spreadsheets',
    'https://www.googleapis.com/auth/script.scriptapp',
    // Needed to tell the script owner (editor) apart from web-app visitors.
    'https://www.googleapis.com/auth/userinfo.email',
  ],
};

function buildAll() {
  return { 'Code.gs': buildCode(), 'Index.html': buildIndex(), 'appsscript.json': JSON.stringify(MANIFEST, null, 2) + '\n' };
}

module.exports = { buildCode, buildIndex, buildAll, MANIFEST };

if (require.main === module) {
  const out = path.join(ROOT, 'dist', 'apps-script');
  fs.mkdirSync(out, { recursive: true });
  const files = buildAll();
  for (const [name, body] of Object.entries(files)) fs.writeFileSync(path.join(out, name), body);
  console.log('Built: ' + Object.entries(files).map(([n, b]) => `${n} (${Math.round(b.length / 1024)} KB)`).join(', '));
}
